# Assignment 4

### Instructions:

Assignment 4 will cover the NumPy and Pandas packages. The overall goal of this assignment is to ensure that you are comfortable with the NumPy and Pandas packages. Follow the steps below to ensure that you receive a passing grade:

    - Complete the following tasks within this notebook
    - When finished, convert this notebook to an HTML/PDF file
    - Place the following items into a zip folder:
        - assignment.HTML or assignment.PDF
        - assignment.ipynb
        - assignment.csv
    - Name this folder using the naming convention: FIRSTNAME_LASTNAME_ASSIGNMENT4.zip
        - For example, if your name was Jane Doe, then the zipped folder should be called JANE_DOE_ASSIGNMENT4.zip
 

In [1]:
# import packages
import numpy as np
import pandas as pd

## 1. Manipulate an Array

Without using the `np.array()` function, manipulate (in any way you choose) a $2 \times 6$ array of zeros, to match the final $4 \times 3$ array shown below.

$$start \rightarrow \begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0
\end{bmatrix} \rightarrow \text{manipulate} \rightarrow
\begin{bmatrix}
12 & 11 & 10\\
9 & 8 & 7\\
10 & 10 & 10\\
3 & 2 & 1\\
\end{bmatrix}$$

In [6]:
target = np.zeros(shape = (2,6))

# your code goes here

target = target.reshape((4, 3))

# Manually fill in the desired values
target[0] = [12, 11, 10]
target[1] = [9, 8, 7]
target[2] = [10, 10, 10]
target[3] = [3, 2, 1]

print(target)

[[12. 11. 10.]
 [ 9.  8.  7.]
 [10. 10. 10.]
 [ 3.  2.  1.]]


## 2. Create a DataFrame and Clean

**A. Create a `DataFrame` using the `pd.DataFrame()` function that is identical to the table below. Remember to use `np.nan` to signify missing values.**

| name | gender | weight_kg | height_cm 
| --- | --- | --- | --- |
| Jacinda | F | 55.51 | **NaN**
| Oralla | M | 60.4 |162.79
| Aeriell | F | **NaN** | 162.32
| Portie | X | 73.94 | 160.33
| Ferdinanda | F | 60.62 | 146.68


In [8]:
# your code goes here

# Create the DataFrame
data = {
    'name': ['Jacinda', 'Oralla', 'Aeriell', 'Portie', 'Ferdinanda'],
    'gender': ['F', 'M', 'F', 'X', 'F'],
    'weight_kg': [55.51, 60.4, np.nan, 73.94, 60.62],
    'height_cm': [np.nan, 162.79, 162.32, 160.33, 146.68]
}

df = pd.DataFrame(data)

print(df)


         name gender  weight_kg  height_cm
0     Jacinda      F      55.51        NaN
1      Oralla      M      60.40     162.79
2     Aeriell      F        NaN     162.32
3      Portie      X      73.94     160.33
4  Ferdinanda      F      60.62     146.68


**B. Replace the missing value in the `weight_kg` column with the mean weight across the `weight_kg` column**

In [9]:
# your code goes here

data = {
    'name': ['Jacinda', 'Oralla', 'Aeriell', 'Portie', 'Ferdinanda'],
    'gender': ['F', 'M', 'F', 'X', 'F'],
    'weight_kg': [55.51, 60.4, np.nan, 73.94, 60.62],
    'height_cm': [np.nan, 162.79, 162.32, 160.33, 146.68]
}

df = pd.DataFrame(data)

# Calculate the mean weight, excluding NaN values
mean_weight = df['weight_kg'].mean()

# Replace the missing value in the weight_kg column with the mean weight
df['weight_kg'].fillna(mean_weight, inplace=True)

print(df)


         name gender  weight_kg  height_cm
0     Jacinda      F    55.5100        NaN
1      Oralla      M    60.4000     162.79
2     Aeriell      F    62.6175     162.32
3      Portie      X    73.9400     160.33
4  Ferdinanda      F    60.6200     146.68


**C. Replace the missing value in the `height_cm` column with the maximum of the heights across the `height_cm` column**

In [13]:
# your code goes here

data = {
    'name': ['Jacinda', 'Oralla', 'Aeriell', 'Portie', 'Ferdinanda'],
    'gender': ['F', 'M', 'F', 'X', 'F'],
    'weight_kg': [55.51, 60.4, np.nan, 73.94, 60.62],
    'height_cm': [np.nan, 162.79, 162.32, 160.33, 146.68]
}

df = pd.DataFrame(data)

# Calculate the maximum height, excluding NaN values
max_height = df['height_cm'].max()

# Replace the missing value in the height_cm column with the maximum height
df['height_cm'].fillna(max_height, inplace=True)

print(df)


         name gender  weight_kg  height_cm
0     Jacinda      F      55.51     162.79
1      Oralla      M      60.40     162.79
2     Aeriell      F        NaN     162.32
3      Portie      X      73.94     160.33
4  Ferdinanda      F      60.62     146.68


**D. Replace the `X` value in the `gender` column with the mode of the `gender` column**

In [14]:
# your code goes here

data = {
    'name': ['Jacinda', 'Oralla', 'Aeriell', 'Portie', 'Ferdinanda'],
    'gender': ['F', 'M', 'F', 'X', 'F'],
    'weight_kg': [55.51, 60.4, np.nan, 73.94, 60.62],
    'height_cm': [np.nan, 162.79, 162.32, 160.33, 146.68]
}

df = pd.DataFrame(data)

# Calculate the mode of the gender column
mode_gender = df['gender'].mode()[0]

# Replace the 'X' value in the gender column with the mode gender
df['gender'] = df['gender'].replace('X', mode_gender)

print(df)

         name gender  weight_kg  height_cm
0     Jacinda      F      55.51        NaN
1      Oralla      M      60.40     162.79
2     Aeriell      F        NaN     162.32
3      Portie      F      73.94     160.33
4  Ferdinanda      F      60.62     146.68


**E. Print the cleaned DataFrame**

In [12]:
# your code goes here

data = {
    'name': ['Jacinda', 'Oralla', 'Aeriell', 'Portie', 'Ferdinanda'],
    'gender': ['F', 'M', 'F', 'X', 'F'],
    'weight_kg': [55.51, 60.4, np.nan, 73.94, 60.62],
    'height_cm': [np.nan, 162.79, 162.32, 160.33, 146.68]
}

df = pd.DataFrame(data)

# Calculate the mean weight, excluding NaN values
mean_weight = df['weight_kg'].mean()

# Replace the missing value in the weight_kg column with the mean weight
df['weight_kg'].fillna(mean_weight, inplace=True)

# Calculate the maximum height, excluding NaN values
max_height = df['height_cm'].max()

# Replace the missing value in the height_cm column with the maximum height
df['height_cm'].fillna(max_height, inplace=True)

# Calculate the mode of the gender column
mode_gender = df['gender'].mode()[0]

# Replace the 'X' value in the gender column with the mode gender
df['gender'] = df['gender'].replace('X', mode_gender)

# Print the cleaned DataFrame
print(df)

         name gender  weight_kg  height_cm
0     Jacinda      F    55.5100     162.79
1      Oralla      M    60.4000     162.79
2     Aeriell      F    62.6175     162.32
3      Portie      F    73.9400     160.33
4  Ferdinanda      F    60.6200     146.68


## 3. DataFrame Manipulation

Let's load in the `exercise` dataset from the `seaborn` package.

In [4]:
import seaborn as sns
exercise = sns.load_dataset("exercise") # this requries an internet connection
print(exercise)

    Unnamed: 0  id     diet  pulse    time     kind
0            0   1  low fat     85   1 min     rest
1            1   1  low fat     85  15 min     rest
2            2   1  low fat     88  30 min     rest
3            3   2  low fat     90   1 min     rest
4            4   2  low fat     92  15 min     rest
..         ...  ..      ...    ...     ...      ...
85          85  29   no fat    135  15 min  running
86          86  29   no fat    130  30 min  running
87          87  30   no fat     99   1 min  running
88          88  30   no fat    111  15 min  running
89          89  30   no fat    150  30 min  running

[90 rows x 6 columns]


### Perform the following tasks on the DataFrame:

**A. Remove the unnamed column from the DataFrame**

In [5]:
# your code goes here

# Load the dataset
exercise = sns.load_dataset("exercise")

# Remove the unnamed column
exercise = exercise.loc[:, ~exercise.columns.str.contains('^Unnamed')]

# Print the DataFrame to verify
print(exercise)

    id     diet  pulse    time     kind
0    1  low fat     85   1 min     rest
1    1  low fat     85  15 min     rest
2    1  low fat     88  30 min     rest
3    2  low fat     90   1 min     rest
4    2  low fat     92  15 min     rest
..  ..      ...    ...     ...      ...
85  29   no fat    135  15 min  running
86  29   no fat    130  30 min  running
87  30   no fat     99   1 min  running
88  30   no fat    111  15 min  running
89  30   no fat    150  30 min  running

[90 rows x 5 columns]


**B. The `time` column is a string type. Use the `.str.split()` function to extract the numbers out of this column. Save these numbers as a new column called `minutes`. What is the data type of this new column? Should it be transformed to a different data type? If so, perform the transformation.**


In [6]:
# your code goes here

# Split the 'time' column and extract the numbers
exercise['minutes'] = exercise['time'].str.split().str[0]

# Check the data type of the new 'minutes' column
print(exercise['minutes'].dtype)

# If the data type is string, transform it to integer
if exercise['minutes'].dtype == 'object':
    exercise['minutes'] = exercise['minutes'].astype(int)

# Verify the transformation
print(exercise['minutes'].dtype)

# Print the updated DataFrame
print(exercise.head())

object
int32
   id     diet  pulse    time  kind  minutes
0   1  low fat     85   1 min  rest        1
1   1  low fat     85  15 min  rest       15
2   1  low fat     88  30 min  rest       30
3   2  low fat     90   1 min  rest        1
4   2  low fat     92  15 min  rest       15


**C. Since we have the `minutes` column, drop the original `time` column from the DataFrame**

In [7]:
# your code goes here

# Drop the original 'time' column
exercise = exercise.drop(columns=['time'])

# Print the updated DataFrame to verify
print(exercise.head())

   id     diet  pulse  kind  minutes
0   1  low fat     85  rest        1
1   1  low fat     85  rest       15
2   1  low fat     88  rest       30
3   2  low fat     90  rest        1
4   2  low fat     92  rest       15


**D. Subset the DataFrame to only contain entries where the `minutes` column is greater than `10`. Use the `.min()` function to determine what is the minimum pulse is for activities that lasted more than `10` minutes**

In [8]:
# your code goes here

subset_exercise = exercise[exercise['minutes'] > 10]

# Determine the minimum pulse for activities that lasted more than 10 minutes
min_pulse = subset_exercise['pulse'].min()

# Print the minimum pulse
print(f"The minimum pulse for activities lasting more than 10 minutes is: {min_pulse}")

The minimum pulse for activities lasting more than 10 minutes is: 82


**E. Use the `groupby()` function to group the `kind` column. Then aggregate to find the mean pulse for each `kind` of activity in the DataFrame**

In [9]:
# your code goes here

# Group by the 'kind' column and aggregate to find the mean pulse for each kind of activity
mean_pulse_by_kind = exercise.groupby('kind')['pulse'].mean()

# Print the result
print(mean_pulse_by_kind)

kind
rest        90.833333
walking     95.200000
running    113.066667
Name: pulse, dtype: float64


**F. Save the DataFrame as a CSV file named `assignment.csv`. Make sure that the `index` argument is set to `False`**

In [12]:
# your code goes here

exercise.to_csv('assignment.csv', index=False)
